/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      "upload.wikimedia.org",
      "images.unsplash.com",
      "cdn.pixabay.com",
      "www.google.com",
      "www.dapurkobe.co.id",
      "resepkoki.id",
      "asset.kompas.com",
      "img-global.cpcdn.com",
      "cdn-brilio-net.akamaized.net",
      "img.kurio.network",
      "akcdn.detik.net.id",
      "static.republika.co.id",
      "media-cdn.tripadvisor.com",
      "storage.googleapis.com",
      "your-cdn.example.com",
      "lh3.googleusercontent.com",
      "example.com",
      "images.unsplash.com",
      "www.thegfrecipes.com",
      "hsph.harvard.edu",
      "source.unsplash.com",
      "cdn.idntimes.com",
      "upload.wikimedia.org",
      "cdn1-production-images-kly.akamaized.net",
      "www.finnafood.com",
      "assets.unileversolutions.com",
      "static.promediateknologi.id",
      "statik.tempo.co",
      "i.gojekapi.com",
      "encrypted-tbn0.gstatic.com",
      "assets.unileversolutions.com",
      "cdn0-production-images-kly.akamaized.net",
      "encrypted-tbn0.gstatic.com",
      "encrypted-tbn0.gstatic.com",
      "www.dapurkobe.co.id",
      "encrypted-tbn0.gstatic.com",
    ],
  },
};

module.exports = nextConfig;
